config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "kudos#index"
  
  devise_scope :admin_user do
    devise_for :admin_users, path: 'admin', controllers: { sessions: "admin_users/sessions" }
    match '/admin', to: 'admin_users/sessions#new', via: 'get'
  end

  devise_for :employees, path: 'employees', controllers: { sessions: "employees/sessions", registrations: "employees/registrations" }

  resources :kudos
  resources :rewards, only: %i[index show] do
    collection do
      resources :orders, only: %i[new create]
      resources :display_orders, only: %i[index]
    end
  end
  
  namespace :admin_users, path: 'admin' do
    resources :kudos, only: %i[index destroy]
    resources :employees, only: %i[index edit update destroy] do
      collection do
        resources :orders, only: %i[index update] do
          collection do
            get 'export_to_csv'
          end
        end
        get 'edit_number_of_available_kudos_for_all'
        patch 'add_available_kudos_for_all'
      end
    end
    resources :company_values, except: %i[show]
    resources :rewards do
      collection do
        get 'new_import_from_csv'
        post 'import_from_csv'
      end
    end
    resources :categories, except: %i[show]
    resources :pages, only: [] do
      collection do
        get :dashboard
      end
    end
    resources :online_codes, except: %i[show] do
      collection do
        get 'new_import_from_csv'
        post 'import_from_csv'
      end
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :given_kudos, class_name: 'Kudo', foreign_key: 'giver', inverse_of: :giver, dependent: :destroy
  has_many :received_kudos, class_name: 'Kudo', foreign_key: 'receiver', inverse_of: :receiver, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :rewards, through: :orders
  has_one :address, dependent: :nullify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, presence: true
  validates :number_of_available_kudos, numericality: { greater_than_or_equal_to: 0 }
  validates :earned_points, numericality: { greater_than_or_equal_to: 0 }

  def full_name
    return email if first_name == 'No' && last_name == 'Name'

    "#{first_name} #{last_name}"
  end
end

app/controllers/admin_users/base_controller.rb
module AdminUsers
  class BaseController < ApplicationController
    before_action :authenticate_admin_user!

    layout 'admin_user'
  end
end

app/controllers/admin_users/categories_controller.rb
module AdminUsers
  class CategoriesController < BaseController
    def index
      render :index, locals: { categories: Category.all.order(title: :asc) }
    end

    def new
      render :new, locals: { category: Category.new }
    end

    def edit
      render :edit, locals: { category: category }
    end

    def create
      record = Category.new(category_params)

      if record.save
        redirect_to admin_users_categories_path, notice: 'Category was successfully created.'
      else
        render :new, locals: { category: record }
      end
    end

    def update
      if category.update(category_params)
        redirect_to admin_users_categories_path, notice: 'Category was successfully updated.'
      else
        render :edit, locals: { category: category }
      end
    end

    def destroy
      if category.destroy
        redirect_to admin_users_categories_url, notice: 'Category was successfully destroyed.'
      else
        redirect_to admin_users_categories_path,
                    notice: 'This category cannot be deleted because of its relations with existing rewards.'
      end
    end

    private

    def category
      @category ||= Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:title)
    end
  end
end

app/controllers/admin_users/company_values_controller.rb
module AdminUsers
  class CompanyValuesController < BaseController
    def index
      render :index, locals: { company_values: CompanyValue.all.order(title: :asc) }
    end

    def new
      render :new, locals: { company_value: CompanyValue.new }
    end

    def edit
      render :edit, locals: { company_value: company_value }
    end

    def create
      record = CompanyValue.new(company_value_params)

      if record.save
        redirect_to admin_users_company_values_path, notice: 'Company Value was successfully created.'
      else
        render :new, locals: { company_value: record }
      end
    end

    def update
      if company_value.update(company_value_params)
        redirect_to admin_users_company_values_path, notice: 'Company Value was successfully updated.'
      else
        render :edit, locals: { company_value: company_value }
      end
    end

    def destroy
      if company_value.destroy
        redirect_to admin_users_company_values_url, notice: 'Company Value was successfully destroyed.'
      else
        redirect_to admin_users_company_values_path,
                    notice: 'This company value cannot be deleted because of its relations with existing kudos.'
      end
    end

    private

    def company_value
      @company_value ||= CompanyValue.find(params[:id])
    end

    def company_value_params
      params.require(:company_value).permit(:title)
    end
  end
end

app/controllers/admin_users/employees_controller.rb
module AdminUsers
  class EmployeesController < BaseController
    def index
      render :index, locals: { employees: Employee.all.order(:email) }
    end

    def edit
      render :edit, locals: { employee: employee }
    end

    def update
      if employee_params[:password].blank?
        return render :edit unless employee.update_without_password(employee_params.except(:password))

        redirect_to admin_users_employees_path, notice: 'Employee was successfully updated.'
      elsif employee.update(employee_params)
        redirect_to admin_users_employees_path, notice: 'Employee was successfully updated.'
      else
        render :edit, locals: { employee: employee }
      end
    end

    def destroy
      employee.destroy
      redirect_to admin_users_employees_path, notice: 'Employee was successfully destroyed.'
    end

    def edit_number_of_available_kudos_for_all; end

    def add_available_kudos_for_all
      added_kudos_params = params[:number_of_added_kudos].to_i
      if added_kudos_params.positive? && added_kudos_params <= 20
        begin
          ActiveRecord::Base.transaction do
            Employee.all.each do |employee|
              employee.increment(:number_of_available_kudos, added_kudos_params).save!
            end
          end
        rescue StandardError
          redirect_to dashboard_admin_users_pages_path, alert: 'Unfortunately something went wrong :('
        else
          redirect_to admin_users_employees_path,
                      notice: "Each employee received #{added_kudos_params} additional kudos for use."
        end
      else
        redirect_to dashboard_admin_users_pages_path,
                    alert: 'Given number is not valid, please enter a number between 1 to 20.'
      end
    end

    private

    def employee
      @employee ||= Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :email, :password, :number_of_available_kudos)
    end
  end
end

app/controllers/admin_users/kudos_controller.rb
module AdminUsers
  class KudosController < BaseController
    def index
      render :index, locals: { kudos: Kudo.includes(:receiver, :giver, :company_value).all.order(created_at: :desc) }
    end

    def destroy
      ActiveRecord::Base.transaction do
        kudo.destroy!
        kudo.giver.increment(:number_of_available_kudos).save!
        kudo.receiver.decrement(:earned_points).save!
      end
      redirect_to admin_users_kudos_path, notice: 'Kudo was successfully destroyed.'
    rescue ActiveRecord::RecordInvalid, ActiveRecord::StatementInvalid => e
      redirect_to admin_users_kudos_path, alert: e.message
    end

    private

    def kudo
      @kudo ||= Kudo.find(params[:id])
    end
  end
end

app/controllers/admin_users/online_codes_controller.rb
module AdminUsers
  class OnlineCodesController < BaseController
    def index
      render :index, locals: { online_codes: OnlineCode.includes(:reward).order(code: :asc) }
    end

    def new
      render :new, locals: { online_code: OnlineCode.new }
    end

    def edit
      render :edit, locals: { online_code: online_code }
    end

    def create
      online_code = OnlineCode.new(online_code_params)

      if online_code.save
        redirect_to admin_users_online_codes_path, notice: 'Online code was successfully created.'
      else
        render :new, locals: { online_code: online_code }
      end
    end

    def update
      if online_code.update(online_code_params)
        redirect_to admin_users_online_codes_path, notice: 'Online code was successfully updated.'
      else
        render :edit, locals: { online_code: online_code }
      end
    end

    def destroy
      if online_code.destroy
        redirect_to admin_users_online_codes_path, notice: 'Online code was successfully destroyed.'
      else
        redirect_to admin_users_online_codes_path, notice: 'Something went wrong :('
      end
    end

    def new_import_from_csv
      render :new_import_from_csv
    end

    def import_from_csv
      online_codes = OnlineCodesImportService.new(params)

      if online_codes.call
        redirect_to admin_users_online_codes_path, notice: 'Online codes were successfully imported.'
      else
        redirect_to admin_users_online_codes_path, alert: online_codes.errors.join('; ')
      end
    end

    private

    def online_code
      @online_code ||= OnlineCode.find(params[:id])
    end

    def online_code_params
      params.require(:online_code).permit(:code, :reward_id)
    end
  end
end

app/controllers/admin_users/orders_controller.rb
require 'csv'

module AdminUsers
  class OrdersController < BaseController
    def index
      render :index, locals: { orders: Order.where(employee: employee).order(:status), employee: employee }
    end

    def update
      if order.status_delivered?
        redirect_back fallback_location: admin_users_employees_path,
                      notice: 'The order has already been delivered.'
      elsif order.update(status: :delivered)
        send_confirmation_email_to_employee
        redirect_back fallback_location: admin_users_employees_path,
                      notice: 'The order has been delivered successfully!'
      else
        redirect_back fallback_location: admin_users_employees_path,
                      notice: 'The order has not been delivered :('
      end
    end

    def export_to_csv
      @orders = Order.includes([:employee]).order(created_at: :desc)

      response.headers['Content-Type'] = 'text/csv'
      response.headers['Content-Disposition'] = "attachment; filename=#{Time.zone.now.to_s(:number)}_orders.csv"
      render template: 'admin_users/orders/orders', formats: [:csv], handlers: [:erb]
    end

    private

    def employee
      @employee ||= Employee.find(params[:employee])
    end

    def order
      @order ||= Order.find(params[:id])
    end

    def send_confirmation_email_to_employee
      if order.reward_snapshot.delivery_method_post?
        EmployeeMailer.post_delivery_confirmation_email(order).deliver_now
      elsif order.reward_snapshot.delivery_method_pick_up?
        EmployeeMailer.pick_up_delivery_confirmation_email(order).deliver_now
      end
    end
  end
end

app/controllers/admin_users/pages_controller.rb
module AdminUsers
  class PagesController < BaseController
    def dashboard; end
  end
end

app/controllers/admin_users/rewards_controller.rb
module AdminUsers
  class RewardsController < BaseController
    def index
      render :index, locals: { rewards: Reward.order(title: :asc).with_attached_photo.includes([:category]) }
    end

    def show
      render :show, locals: { reward: reward }
    end

    def new
      render :new, locals: { reward: Reward.new }
    end

    def edit
      render :edit, locals: { reward: reward }
    end

    def create
      record = Reward.new(reward_params)

      if record.save
        redirect_to admin_users_rewards_path, notice: 'Reward was successfully created.'
      else
        render :new, locals: { reward: record }
      end
    end

    def update
      if reward.update(reward_params)
        redirect_to admin_users_rewards_path, notice: 'Reward was successfully updated.'
      else
        render :edit, locals: { reward: reward }
      end
    end

    def destroy
      reward.destroy
      redirect_to admin_users_rewards_path, notice: 'Reward was successfully deleted.'
    end

    def new_import_from_csv
      render :new_import_from_csv, locals: { reward: Reward.new }
    end

    def import_from_csv
      rewards_import_service = RewardsImportService.new(params)

      if rewards_import_service.call
        redirect_to admin_users_rewards_path, notice: 'Rewards were successfully imported.'
      else
        redirect_to admin_users_rewards_path, alert: rewards_import_service.errors.join('; ')
      end
    end

    private

    def reward
      @reward ||= Reward.find(params[:id])
    end

    def reward_params
      params.require(:reward).permit(:title, :description, :price, :category_id, :delivery_method, :photo)
    end
  end
end

app/controllers/admin_users/sessions_controller.rb
# frozen_string_literal: true

module AdminUsers
  class SessionsController < Devise::SessionsController
    include Accessible
    before_action :check_employee

    layout 'admin_user'

    def after_sign_in_path_for(_resource)
      dashboard_admin_users_pages_path
    end
  end
end

app/controllers/employees/registrations_controller.rb
# frozen_string_literal: true

module Employees
  class RegistrationsController < Devise::RegistrationsController
    include Accessible
    before_action :check_admin
  end
end

app/controllers/employees/sessions_controller.rb
# frozen_string_literal: true

module Employees
  class SessionsController < Devise::SessionsController
    include Accessible
    before_action :check_admin
  end
end

app/views/admin_users/employees/edit.html.erb
<div class="card mt-5">
  <div class="card-header">
    <h2>Edit employee</h2>
  </div>
 
  <div class="card-body">
    <%= form_with(model: [:admin_users, @employee]) do |form| %>
      <div class="form-group mt-3">
        <% @employee.errors.each do |error| %>
          <li><strong><%= error.full_message %></strong></li>
        <% end %>
      </div>

      <div class="row">
        <div class="col">
          <%= form.text_field :first_name, autofocus: true, autocomplete: "first-name", class:"form-control", placeholder:"First Name" %>
        </div>
        <div class="col">
          <%= form.text_field :last_name, autofocus: true, autocomplete: "last-name", class:"form-control", placeholder:"Last Name" %>
        </div>
      </div>

      <div class="field form-group mt-3">
        <%= form.email_field :email, autofocus: true, autocomplete: "email", class:"form-control", placeholder:"Email" %>
      </div>
       
      <div class="field form-group mt-3">
        <%= form.password_field :password, autocomplete: "new-password", class: "form-control", placeholder:"Password" %>
      </div>

      <div class="field form-group mt-3">
        <%= form.number_field :number_of_available_kudos, in: 0..10, autofocus: true, class:"form-control", placeholder:"Number of kudos" %>
      </div>

      <div class="actions mt-3">
        <%= form.submit "Update", class: "btn btn-dark"%>
      </div>
    <% end %>

<%= link_to "Back", admin_users_employees_path, class: 'btn btn-outline-secondary mt-3' %>

app/views/admin_users/employees/edit_number_of_available_kudos_for_all.html.erb
<div class="card mt-4">
  <div class="card-header">
    <h2>Increase the number of kudos available for each employee by a number from 1 to 20</h2>
  </div>

  <div class="card-body">
    <%= form_with url: "add_available_kudos_for_all", method: :patch do |form| %>

      <div class="field form-group">
        <%= form.number_field :number_of_added_kudos, in: 1..20, autofocus: true, class: "form-control", placeholder: "Number of kudos" %>
      </div>
      
      <div class="actions mt-3">
        <%= form.submit "Add Kudos", data: { confirm: "Are you sure?" }, class: "btn btn-dark" %>
      </div>
    <% end %>
    <%= link_to "Back to Admin Dashboard", dashboard_admin_users_pages_path, class:"btn btn-outline-secondary mt-3" %>
  </div>
</div>

app/views/admin_users/employees/index.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover table caption-top">
    <caption class="text-center"><h1>Employees Admin Panel &#128110;</h1></caption>
    <thead class="table-dark">
      <tr class="text-center">
        <th>Full Name</th>
        <th>Email</th>
        <th>Available kudos</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% employees.each do |employee| %>
        <tr class="text-center">
          <td><%= employee.first_name + ' ' + employee.last_name %></td>
          <td><%= employee.email %></td>
          <td><%= employee.number_of_available_kudos %></td>
          <td>
            <div class="btn-group">
              <button type="button" class="btn btn-primary dropdown-toggle position-relative" data-bs-toggle="dropdown" aria-expanded="false">
                Actions
                <% if employee.orders.where(status: :not_delivered).any? %>
                  <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
                    <span class="visually-hidden">New alerts</span>
                  </span>
                <% end %>
              </button>
              <ul class="dropdown-menu dropdown-menu-dark">
                <li><%= link_to 'Edit', edit_admin_users_employee_path(employee), class: 'dropdown-item' %></li>
                <li class="position-relative">
                  <%= link_to "Orders", admin_users_orders_path(employee: employee), class: 'dropdown-item' %>
                  <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                    <%= employee.orders.where(status: :not_delivered).count %>
                    <span class="visually-hidden">undelivered orders</span>
                  </span>
                </li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to 'Destroy', admin_users_employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' }, class:'dropdown-item' %></li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Back to Admin Dashboard', dashboard_admin_users_pages_path, class:'btn btn-outline-secondary' %>
  <%= link_to 'Export all orders to CSV', export_to_csv_admin_users_orders_path, class:'btn btn-outline-success' %>
</div>