config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "kudos#index"
  
  devise_scope :admin_user do
    devise_for :admin_users, path: 'admin', controllers: { sessions: "admin_users/sessions" }
    match '/admin', to: 'admin_users/sessions#new', via: 'get'
  end

  devise_for :employees, path: 'employees', controllers: { sessions: "employees/sessions", registrations: "employees/registrations" }

  resources :kudos
  resources :rewards, only: %i[index show] do
    collection do
      resources :orders, only: %i[new create]
      resources :display_orders, only: %i[index]
    end
  end
  
  namespace :admin_users, path: 'admin' do
    resources :kudos, only: %i[index destroy]
    resources :employees, only: %i[index edit update destroy] do
      collection do
        resources :orders, only: %i[index update] do
          collection do
            get 'export_to_csv'
          end
        end
        get 'edit_number_of_available_kudos_for_all'
        patch 'add_available_kudos_for_all'
      end
    end
    resources :company_values, except: %i[show]
    resources :rewards do
      collection do
        get 'new_import_from_csv'
        post 'import_from_csv'
      end
    end
    resources :categories, except: %i[show]
    resources :pages, only: [] do
      collection do
        get :dashboard
      end
    end
    resources :online_codes, except: %i[show] do
      collection do
        get 'new_import_from_csv'
        post 'import_from_csv'
      end
    end
  end
end

app/models/kudo.rb
class Kudo < ApplicationRecord
  belongs_to :giver, class_name: 'Employee', inverse_of: :given_kudos
  belongs_to :receiver, class_name: 'Employee', inverse_of: :received_kudos
  belongs_to :company_value

  validates :title, :content, presence: true
end

app/controllers/admin_users/kudos_controller.rb
module AdminUsers
  class KudosController < BaseController
    def index
      render :index, locals: { kudos: Kudo.includes(:receiver, :giver, :company_value).all.order(created_at: :desc) }
    end

    def destroy
      ActiveRecord::Base.transaction do
        kudo.destroy!
        kudo.giver.increment(:number_of_available_kudos).save!
        kudo.receiver.decrement(:earned_points).save!
      end
      redirect_to admin_users_kudos_path, notice: 'Kudo was successfully destroyed.'
    rescue ActiveRecord::RecordInvalid, ActiveRecord::StatementInvalid => e
      redirect_to admin_users_kudos_path, alert: e.message
    end

    private

    def kudo
      @kudo ||= Kudo.find(params[:id])
    end
  end
end

app/controllers/kudos_controller.rb
class KudosController < ApplicationController
  before_action :authenticate_employee!, except: %i[index show]
  before_action :correct_employee?, only: %i[edit update destroy]
  before_action :can_add_another_kudo?, only: %i[new create]

  def index
    render :index, locals: { kudos: Kudo.includes(:receiver, :giver, :company_value).all.order(created_at: :desc) }
  end

  def show
    render :show, locals: { kudo: kudo }
  end

  def new
    render :new, locals: { kudo: Kudo.new }
  end

  def edit
    render :edit, locals: { kudo: kudo }
  end

  def create
    record = Kudo.new(kudo_params)
    record.giver = current_employee

    if record.save
      current_employee.decrement(:number_of_available_kudos).save
      record.receiver.increment(:earned_points).save
      redirect_to kudos_path, notice: 'Kudo was successfully created.'
    else
      render :new, locals: { kudo: record }
    end
  end

  def update
    authorize kudo

    if params.dig(:kudo, :receiver_id).to_i != kudo.receiver.id
      previous_receiver = kudo.receiver
      if kudo.update(kudo_params)
        kudo.receiver.increment(:earned_points).save
        previous_receiver.decrement(:earned_points).save
        redirect_to kudo, notice: 'Kudo was successfully updated.'
      else
        render :edit, locals: { kudo: kudo }
      end
    elsif kudo.update(kudo_params)
      redirect_to kudo, notice: 'Kudo was successfully updated.'
    else
      render :edit, locals: { kudo: kudo }
    end
  end

  def destroy
    authorize kudo

    ActiveRecord::Base.transaction do
      kudo.destroy!
      kudo.giver.increment(:number_of_available_kudos).save!
      kudo.receiver.decrement(:earned_points).save!
    end
    redirect_to kudos_path, notice: 'Kudo was successfully destroyed.'
  rescue ActiveRecord::RecordInvalid, ActiveRecord::StatementInvalid => e
    redirect_to kudos_path, alert: e.message
  end

  private

  def kudo
    @kudo ||= Kudo.find(params[:id])
  end

  def kudo_params
    params.require(:kudo).permit(:title, :content, :giver_id, :receiver_id, :company_value_id)
  end

  def correct_employee?
    return if kudo.giver == current_employee

    redirect_to kudos_path, notice: 'Not authorized to edit this Kudo.'
  end

  def can_add_another_kudo?
    return if current_employee.number_of_available_kudos.positive?

    redirect_to kudos_path, notice: 'You cannot add more kudos.'
  end
end

app/views/kudos/_form.html.erb
<%= form_with(model: kudo) do |form| %>
  <% if kudo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kudo.errors.count, "error") %> prohibited this kudo from being saved:</h2>

      <ul>
        <% kudo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group mb-3">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control", placeholder:"Title" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.label :content %>
    <%= form.text_area :content, class:"form-control", placeholder:"Content" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.label :receiver_id %>
    <%= form.collection_select :receiver_id, Employee.where.not(id: current_employee.id), :id, :full_name %>
  </div>

  <div class="field form-group mb-3">
    <%= form.label :company_value_id %>
    <%= form.collection_select :company_value_id, CompanyValue.order(title: :asc), :id, :title, prompt: true %>
  </div>
  
  <div class="actions mb-3">
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>

app/views/kudos/edit.html.erb
<h1>Editing Kudo</h1>

<%= render 'form', kudo: kudo %>

<%= link_to 'Show', kudo %> |
<%= link_to 'Back', kudos_path %>

app/views/kudos/index.html.erb
<div class="table-responsive">
  <% if employee_signed_in? %>
    <table class="table table-striped table-bordered table-hover table caption-top">
      <caption class="text-center"><h1>Kudos &#128509;</h1></caption>
      <thead class="table-dark">
        <tr class="text-center">
          <th>Title</th>
          <th>Content</th>
          <th>Giver</th>
          <th>Receiver</th>
          <th>Company Value</th>
          <th colspan="2">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% kudos.each do |kudo| %>
          <tr class="text-center">
            <td><%= link_to kudo.title, kudo %></td>
            <td><%= kudo.content %></td>
            <td><%= kudo.giver.full_name %></td>
            <td><%= kudo.receiver.full_name %></td>
            <td><%= kudo.company_value.title %></td>
            <% if kudo.giver == current_employee %>
              <% if policy(kudo).update? && policy(kudo).destroy? %>
                <td><%= link_to 'Edit', edit_kudo_path(kudo), class:'btn btn-outline-primary' %></td>
                <td><%= button_to 'Destroy', kudo, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-outline-danger' %></td>
              <% else %>
                <td><%= link_to 'Edit', edit_kudo_path(kudo), class:'btn btn-outline-primary disabled', aria: { hidden: true } %></td>
                <td><%= button_to 'Destroy', kudo, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-outline-danger', disabled: true, aria: { hidden: true } %></td>
              <% end %>
            <% else %>
              <td><%= link_to 'Unauthorized', kudos_path, class:'btn btn-outline-warning' %></td>
              <td><%= link_to 'Unauthorized', kudos_path, class:'btn btn-outline-warning' %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>  
  <% else %>
    <h1 class="text-center">You have to be logged in to view the kudos list &#128576;</h1>
    <div style="text-align:center;">
      <iframe width="560" height="315" src="https://www.youtube.com/embed/zmte5lUh5Vc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
  <% end %>
</div>

app/views/kudos/new.html.erb
<h1>New Kudo</h1>

<%= render 'form', kudo: kudo %>

<%= link_to 'Back', kudos_path %>

app/views/kudos/show.html.erb
<div class="shadow p-3 mb-5 bg-body rounded">
  <figure class="text-end">
    <figcaption class="block-footer">
      <strong>Giver:</strong>
      <%= kudo.giver.full_name %>
    </figcaption>

    <figcaption class="block-footer">
      <strong>Receiver:</strong>
      <%= kudo.receiver.full_name %>
    </figcaption>
  </figure>

  <h2 class="display-6">
    <strong>Title:</strong>
    <%= kudo.title %>
  </h2>

   <h3 class="display-8">
    Company value:
    <%= kudo.company_value.title %>
  </h3>

  <p class="lead">
    <em><%= kudo.content %></em>
  </p>

  <% if kudo.giver == current_employee %>
   <% if policy(kudo).update? %>
      <%= link_to 'Edit', edit_kudo_path(kudo), class:'btn btn-dark' %>
    <% else %>
      <%= link_to 'Edit', edit_kudo_path(kudo), class:'btn btn-dark disabled', aria: { hidden: true } %>
    <% end %>
  <% end %>
  <%= link_to 'Back', kudos_path, class:"btn btn-dark"%>
</div>