config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "kudos#index"
  
  devise_scope :admin_user do
    devise_for :admin_users, path: 'admin', controllers: { sessions: "admin_users/sessions" }
    match '/admin', to: 'admin_users/sessions#new', via: 'get'
  end

  devise_for :employees, path: 'employees', controllers: { sessions: "employees/sessions", registrations: "employees/registrations" }

  resources :kudos
  resources :rewards, only: %i[index show] do
    collection do
      resources :orders, only: %i[new create]
      resources :display_orders, only: %i[index]
    end
  end
  
  namespace :admin_users, path: 'admin' do
    resources :kudos, only: %i[index destroy]
    resources :employees, only: %i[index edit update destroy] do
      collection do
        resources :orders, only: %i[index update] do
          collection do
            get 'export_to_csv'
          end
        end
        get 'edit_number_of_available_kudos_for_all'
        patch 'add_available_kudos_for_all'
      end
    end
    resources :company_values, except: %i[show]
    resources :rewards do
      collection do
        get 'new_import_from_csv'
        post 'import_from_csv'
      end
    end
    resources :categories, except: %i[show]
    resources :pages, only: [] do
      collection do
        get :dashboard
      end
    end
    resources :online_codes, except: %i[show] do
      collection do
        get 'new_import_from_csv'
        post 'import_from_csv'
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/views/home/_admin_user_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'ADMIN | Employee Recognition Platform', dashboard_admin_users_pages_path, class:"navbar-brand" %>
  
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if admin_user_signed_in? %>
        <li class="nav-item">
            <%= link_to 'Kudos', admin_users_kudos_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Employees', admin_users_employees_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Company Values', admin_users_company_values_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Rewards', admin_users_rewards_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Categories', admin_users_categories_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Online Codes', admin_users_online_codes_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_admin_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', new_admin_user_session_path, class:"nav-link" %>
          </li>  
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Employee Recognition Platform', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if admin_user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_admin_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% elsif employee_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "Available kudos: #{current_employee.number_of_available_kudos}" %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to 'New Kudo', new_kudo_path, class:"dropdown-item" %></li>
            </ul>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "Points: #{current_employee.earned_points}" %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to 'Rewards', rewards_path, class:"dropdown-item" %></li>
              <li><%= link_to 'My Rewards', display_orders_path, class:"dropdown-item" %></li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to 'Edit Profile', edit_employee_registration_path, class:"dropdown-item" %></li>
              <li><%= link_to 'Sign out', destroy_employee_session_path, method: :delete, class:"dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign up', new_employee_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign in', new_employee_session_path, class:"nav-link" %>
          </li>  
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
Hello World